Update README.md
Project-MONAI/monai-deploy-storage pull request #2
Opened 2022-04-06 20:16 UTC by mocsharp

2022-04-06 22:12 UTC, dbericat requested changes
Looks good besides a couple comments.

2022-04-06 22:12 UTC, dbericat commented on README.md
> +The MONAI Deploy Storage library for MONAI Deploy clinical data pipelines system enables users to extend the system to external storage services by implementing the [IStorageService API](src/Storage/
Check double space '.  The API'

2022-04-07 00:24 UTC, mocsharp commented on README.md
> +Ask and answer questions over on [MONAI Deploy's GitHub Discussions tab](https://github.com/Project-MONAI/monai-deploy/discussions).
Updated to https://github.com/Project-MONAI/monai-deploy-storage/discussions

2022-04-07 00:24 UTC, mocsharp commented on README.md
> +The MONAI Deploy Storage library for MONAI Deploy clinical data pipelines system enables users to extend the system to external storage services by implementing the [IStorageService API](src/Storage/
Fixed.

2022-04-07 17:27 UTC, merged